# Task 1.3

## Task 1.3.1

In [24]:
import numpy as np

In [25]:
a = np.zeros((8, 8), dtype = int)

In [26]:
a[1::2, ::2] = 1
a[::2, 1::2] = 1

In [27]:
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Task 1.3.2

In [28]:
import numpy as np

In [29]:
a = np.zeros((5, 5))
a += np.arange(5)

In [30]:
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Task 1.3.3

In [40]:
import numpy as np

In [41]:
a = np.random.random((3, 3, 3))

In [42]:
print(a)

[[[0.05973908 0.46834771 0.67593537]
  [0.54468457 0.42470509 0.4015881 ]
  [0.787482   0.39396605 0.07327334]]

 [[0.91123508 0.27271211 0.33843807]
  [0.61549271 0.27726736 0.21525161]
  [0.6711232  0.52954013 0.85621327]]

 [[0.42649391 0.35555845 0.88017446]
  [0.21570598 0.62760181 0.3207202 ]
  [0.48870655 0.06417596 0.85611688]]]


## Task 1.3.4

In [46]:
import numpy as np

In [47]:
a = np.ones((6, 6), dtype = int)
a[1:-1, 1:-1] = 0

In [48]:
print(a)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


## Task 1.3.5

In [49]:
import numpy as np

In [50]:
a = np.array([1, 6, 8, 3, 7, 2])

In [51]:
print(np.sort(a)[::-1])

[8 7 6 3 2 1]


## Task 1.3.6

In [52]:
import numpy as np

In [53]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]])

In [54]:
print(a)
print(a.shape)
print(a.size)
print(a.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)
15
2


# Task 2.3

## Task 2.3.1

In [55]:
import pandas as pd
import numpy as np

In [56]:
s1 = pd.Series([34, 72], index=['x', 'y'])
s2 = pd.Series([58, 86], index=['x', 'y'])

In [57]:
r = np.sqrt(np.sum((s1 - s2)**2))

In [58]:
print(r)

27.784887978899608


## Task 2.3.2

In [4]:
import pandas as pd

In [5]:
url="https://github.com/akmand/datasets/raw/main/abolone.csv"
df = pd.read_csv(url)

In [6]:
print(df.head(5))

  Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  Rings  
0          0.1010         0.150     15  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10  
4          0.0395         0.055      7  


## Task 2.3.3

In [1]:
import pandas as pd

In [2]:
url="https://github.com/akmand/datasets/raw/main/abolone.csv"
df = pd.read_csv(url)

In [3]:
print('2.2.5')
print(df.head(5))
print(df.tail(3))
print(df.shape)
print(df.describe())

2.2.5
  Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  Rings  
0          0.1010         0.150     15  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10  
4          0.0395         0.055      7  
     Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
4174      M   0.600     0.475   0.205        1.1760          0.5255   
4175      F   0.625     0.485   0.150        1.0945          0.5310   
4176      M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
4174      

In [4]:
print('2.2.6')
print(df.iloc[2:6])

2.2.6
  Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
5      I   0.425     0.300   0.095        0.3515          0.1410   

   Viscera weight  Shell weight  Rings  
2          0.1415         0.210      9  
3          0.1140         0.155     10  
4          0.0395         0.055      7  
5          0.0775         0.120      8  


In [5]:
print('2.2.7')
print(df[df['Gender'] == 'M'].tail(5))

2.2.7
     Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
4170      M    0.55     0.430   0.130        0.8395          0.3155   
4171      M    0.56     0.430   0.155        0.8675          0.4000   
4173      M    0.59     0.440   0.135        0.9660          0.4390   
4174      M    0.60     0.475   0.205        1.1760          0.5255   
4176      M    0.71     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
4170          0.1955        0.2405     10  
4171          0.1720        0.2290      8  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4176          0.3765        0.4950     12  


# Task 3.3

## Task 3.3.2

In [1]:
import pandas as pd
from sklearn import preprocessing

In [2]:
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
df = pd.read_csv(url)

In [3]:
minmax=preprocessing.MinMaxScaler(feature_range=(0, 1))
zscaler=preprocessing.StandardScaler()
df[["sepal_length_cm"]]=minmax.fit_transform(df[["sepal_length_cm"]])
df[["sepal_width_cm"]]=zscaler.fit_transform(df[["sepal_width_cm"]])

In [4]:
print(df)

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145 